# -*- coding: utf-8 -*-
"""Loops_Assignment_SMIT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Svv_8_YK3dhSukwjfC04_KGxwkRm6VVj
"""

def print_numbers():
    for i in range(1, 11):
        print(i)

# Example usage
print_numbers()

def print_numbers_reverse():
    i = 20
    while i >= 1:
        print(i)
        i -= 1

# Example usage
print_numbers_reverse()

def print_even_numbers():
    for i in range(1, 11):
        if i % 2 == 0:
            print(i)

# Example usage
print_even_numbers()

def reverse_string():
    user_string = input("Enter a string: ")
    reversed_string = user_string[::-1]
    print(f"Reversed string: {reversed_string}")

# Example usage
reverse_string()

def print_numbers_upto_n():
    n = int(input("Enter a number: "))
    for i in range(1, n + 1):
        print(i)

# Example usage
print_numbers_upto_n()

def print_numbers_upto_n():
    n = int(input("Enter a number: "))
    for i in range(1, n + 1):
        print(i)

# Example usage
print_numbers_upto_n()

def happy_birthday():
    for _ in range(5):
        print("Happy Birthday!")

# Example usage
happy_birthday()

def generate_squared_series():
    n = int(input("Enter a number: "))
    print(f"The first {n} terms of the series are:")
    for i in range(1, n + 1):
        print(i ** 2, end=" ")

# Example usage
generate_squared_series()

def multiplication_table():
    n = int(input("Enter a number: "))
    for i in range(1, 11):
        print(f"{n} x {i} = {n * i}")

# Example usage
multiplication_table()

